---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'creates an iam user & group, assigns the user to the group, sets up https codecommit credentials'
Parameters:
  username:
    Type: String
    Default: ""
    Description: Name for the CodeCommit User
Resources:
  iamUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: 
       !Ref username
  iamkeys:
    DependsOn: iamUser
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref username
  iamGroup:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: admin
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AdministratorAccess
  addUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: 
        !Ref iamGroup
      Users: 
      - !Ref iamUser
  HttpsCredsCustomResource:
    DependsOn: addUserToGroup
    Type: "Custom::LambdaHttpsCreds" # or AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !ImportValue sharedinf-httpscredsarn # The ARN of the lambda function - only mandatory property
      # "Provider Defined Properties" Below..
      user: !Ref username
Outputs:
  adminakid:
    Description: Support Access Key ID
    Value: !Ref iamkeys
  adminsecretkey:
    Description: Support Secret Access Key
    Value: !GetAtt iamkeys.SecretAccessKey
  httpscredsusername:
    Description: IAM User CodeCommit HTTPS credentials username
    Value: !GetAtt HttpsCredsCustomResource.ServiceUserName
  httpscredspassword:
    Description: IAM User CodeCommit HTTPS credentials password
    Value: !GetAtt HttpsCredsCustomResource.ServicePassword


  

